name: CI
on:
  pull_request:
    branches:
      - main
      - test
jobs:
  lint:
    name: â¬£ ESLint
    runs-on: ubuntu-latest
    environment: development
    env:
      NODE_ENV: development
      NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
      NEXTAUTH_URL: http://localhost:3000
      DATABASE_URL: postgresql://coffeebreak:Wizeliner@localhost:5432/wizeline?schema=public
      GOOGLE_CLIENT_ID: 639105917020-i6a7ppdnt1nmalqadr97dm6t3v0mngii.apps.googleusercontent.com
      GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
    steps:
      - name: ğŸ›‘ Cancel Previous Runs
        if: ${{ env.GITHUB_ACTOR != 'nektos/act' }}
        uses: styfle/cancel-workflow-action@0.11.0

      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v3

      - name: â” Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Dump ENV 
        run: echo "$GITHUB_CONTEXT"
        
      - name: ğŸ“¥ Download deps
        uses: bahmutov/npm-install@v1
        with: 
          working-directory: wizeline-os-ai-tools
          useLockFile: false
        
      - name: ğŸ”¬ Lint
        run: npm run lint
        working-directory: wizeline-os-ai-tools

  typecheck:
    name: Ê¦ TypeScript
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ›‘ Cancel Previous Runs
        if: ${{ env.GITHUB_ACTOR != 'nektos/act' }}
        uses: styfle/cancel-workflow-action@0.11.0

      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v3

      - name: â” Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: ğŸ“¥ Download deps
        uses: bahmutov/npm-install@v1
        with: 
          working-directory: wizeline-os-ai-tools
          useLockFile: false

      - name: ğŸ” Type check
        run: npm run typecheck --if-present
        working-directory: wizeline-os-ai-tools

  cypress:
    name: âš«ï¸ Cypress
    runs-on: ubuntu-latest
    environment: development
    env:
      NODE_ENV: development
      NEXTAUTH_URL: http://localhost:3000
      DATABASE_URL: postgresql://coffeebreak:Wizeliner@localhost:5432/wizeline?schema=public
    steps:
      - name: ğŸ›‘ Cancel Previous Runs
        if: ${{ env.GITHUB_ACTOR != 'nektos/act' }}
        uses: styfle/cancel-workflow-action@0.11.0

      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v3

      - name: ğŸ„ Copy test env vars
        run: cp .env.example .env
        working-directory: wizeline-os-ai-tools

      - name: â” Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: harmon758/postgresql-action@v1
        with:
          postgresql version: "12"
          postgresql db: lab_test
          postgresql user: lab_user
          postgresql password: lab_pass

      - name: ğŸ“¥ Download deps
        uses: bahmutov/npm-install@v1
        with:
          working-directory: wizeline-os-ai-tools

      - name: ğŸ›  Setup Database
        run: npx prisma migrate reset --force
        working-directory: wizeline-os-ai-tools

      - name: âš™ï¸ Build
        run: npm run build
        working-directory: wizeline-os-ai-tools

      - name: ğŸŒ³ Cypress run
        uses: cypress-io/github-action@v5
